import { createAmarsiaClient } from "./client";
import type {
  AmarsiaClient,
  AgentController,
  ConversationController,
  RunController,
  StreamController,
  TriggerController
} from "./client";
import { AmarsiaSdkError } from "./errors";
import type {
  AmarsiaSdkErrorData,
  AmarsiaStatus,
  AgentClientToolContext,
  AgentClientToolHandler,
  AgentClientTools,
  AgentContinueOptions,
  AgentGetOptions,
  AgentHistoryItem,
  AgentHistoryPageInfo,
  AgentHistoryResponse,
  AgentLoadMoreHistoryOptions,
  AgentLoadMoreMessagesOptions,
  AgentMessagesPageInfo,
  AgentOpenOptions,
  AgentPendingToolCall,
  AgentProgress,
  AgentRunStatus,
  AgentStartOptions,
  AgentState,
  AgentStatus,
  AgentToolSummary,
  ChatConversation,
  ClientCapability,
  ClientToolCall,
  ClientToolHandler,
  ClientToolResult,
  ConversationData,
  ConversationListResponse,
  ConversationMessagesResponse,
  ConversationMessage,
  ConversationRunOptions,
  ConversationSendRequest,
  ConversationStreamOptions,
  ConversationState,
  CreateTriggerRequest,
  InitConfig,
  ListConversationsRequest,
  LoadMessagesRequest,
  MessageContent,
  MessageFileContent,
  MessageRole,
  MessageTextContent,
  RunRequest,
  RunResponse,
  StatefulResult,
  StreamRequest,
  StreamResponse,
  TriggerData,
  UsageMetadata
} from "./types";

export const amarsia = {
  init: createAmarsiaClient
};

export { createAmarsiaClient, AmarsiaSdkError };
export type {
  AmarsiaClient,
  AgentController,
  ConversationController,
  RunController,
  StreamController,
  TriggerController
};
export type {
  AmarsiaSdkErrorData,
  AmarsiaStatus,
  AgentClientToolContext,
  AgentClientToolHandler,
  AgentClientTools,
  AgentContinueOptions,
  AgentGetOptions,
  AgentHistoryItem,
  AgentHistoryPageInfo,
  AgentHistoryResponse,
  AgentLoadMoreHistoryOptions,
  AgentLoadMoreMessagesOptions,
  AgentMessagesPageInfo,
  AgentOpenOptions,
  AgentPendingToolCall,
  AgentProgress,
  AgentRunStatus,
  AgentStartOptions,
  AgentState,
  AgentStatus,
  AgentToolSummary,
  ChatConversation,
  ClientCapability,
  ClientToolCall,
  ClientToolHandler,
  ClientToolResult,
  ConversationData,
  ConversationListResponse,
  ConversationMessagesResponse,
  ConversationMessage,
  ConversationRunOptions,
  ConversationSendRequest,
  ConversationStreamOptions,
  ConversationState,
  CreateTriggerRequest,
  InitConfig,
  ListConversationsRequest,
  LoadMessagesRequest,
  MessageContent,
  MessageFileContent,
  MessageRole,
  MessageTextContent,
  RunRequest,
  RunResponse,
  StatefulResult,
  StreamRequest,
  StreamResponse,
  TriggerData,
  UsageMetadata
};
